### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by fennifith** [fennifith/Attribouter#38]
Multiple threads. Multithreading. The act of having more than one thread at a single point in time.

**Comment by TheAndroidMaster** [comment]
This was originally created because I _thought_ that there was about a second of lag upon opening the screen. However, it may have been caused by a different issue entirely.

Upon looking into it, I decided to take a quick look at the GitHubData class to see if I could make it any faster at fetching information, and I realized that... it wasn't caching any of the requests. Why? The folder that it was storing the cache in didn't exist.

So commit f818f1f may have resolved this. I'm going to leave it open for a bit and see how the changes affect some of Attribouter's implementations though, just in case there is anything else I can do.

**Comment by rroyGit** [comment]
If it's not solved, I give it a try

**Comment by rroyGit** [comment]
just submitted a PR, can you test with changes? I haven't done too much testing, got some problems when adding the library externally to Android Studio and API compatibility problems when using the library.

Thanks

**Comment by rroyGit** [comment]
Yo, I was wondering for GitHubData class, when creating the class object is it possible to pass the context at that time? If yes, I would like to try moving threads around in that class.
Could you also pinpoint me where you are creating the GitHubData objects? Thanks.

**Comment by TheAndroidMaster** [comment]
@rroyGit GitHubData's subclasses are created in the ["-Wedge" classes](https://github.com/TheAndroidMaster/Attribouter/tree/master/attribouter/src/main/java/me/jfenn/attribouter/wedges). They're then passed to [addRequest](https://github.com/TheAndroidMaster/Attribouter/blob/master/attribouter/src/main/java/me/jfenn/attribouter/wedges/Wedge.java#L99) and end up in the [AttribouterFragment](https://github.com/TheAndroidMaster/Attribouter/blob/master/attribouter/src/main/java/me/jfenn/attribouter/fragments/AboutFragment.java#L172), which adds them to a List and starts them only if they don't already exist in the list (if the same 'request' is created by two Wedges, for example). Otherwise, it either merges them together by combining their listeners, or if the request is finished it just sends it back to the Wedge through [onInit](https://github.com/TheAndroidMaster/Attribouter/blob/master/attribouter/src/main/java/me/jfenn/attribouter/wedges/Wedge.java#L134).
