### ISSUE TITLE
AppWedge description attribute seems to do nothing

### ISSUE THREAD

**Issue by divadsn** [fennifith/Attribouter#71]
Hey James,

In [me.jfenn.attribouter.wedges.AppWedge#L23](https://github.com/fennifith/Attribouter/blob/main/attribouter/src/main/java/me/jfenn/attribouter/wedges/AppWedge.kt#L23) and also in both wikis there is the `description` attribute referenced, but when I tried to migrate from 0.1.5, it's nowhere used in the new UI:

![Screenshot_20210202_160606](https://user-images.githubusercontent.com/28547847/106619158-9118db80-6570-11eb-956b-5ad49e68a48b.png)

Is the attribute deprecated or not implemented yet?

**Comment by fennifith** [comment]
Yeah - it's no longer used in the layout. The string is still there, so if you override the [`attribouter_item_app_info`](https://github.com/fennifith/Attribouter/blob/a38e9cd18597aa9d8516ebf9224f4b8322718a44/attribouter/src/main/res/layout/attribouter_item_app_info.xml) layout in your app you can still use it by adding a view with `id=description`, otherwise it won't do anything. I'll update the wiki to specify that it has been removed.

If you still want a description or something in your app, you can use a [TextWedge](https://jfenn.me/projects/attribouter/wiki/TextWedge.html), which also supports HTML formatting - in my apps, I decided that most people looking at the about screen should already know what the app does, so the description was a bit redundant (thus why I was okay with removing it).

**Comment by divadsn** [comment]
Ah, alright, thanks for the tip with the TextWedge, I always had the description in place as a tagline :)
